language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: MxivrEvf+2diO3fPgDTvRdNxuWtQ/eZYwfhmmiSIVj01jg25bXU4Qv5Bt/UrbDo5LRk7TfsUQndsst/Qw41OeemSvoAGpuILtmXRY4LZyACo+bpoYwU92px0dxRQN8Z3ScP+54rYO7N07FUSGo/w+KY3e0jHwHfaIe2UZr4ZHHnFnVpKsR1GJdPLZ8gqS51KRBdQcG94C6QndRooQv2PJ2kNxUlXVVNEJvfAQuSOWAMoeaS+XFnBUWGgm/px1ncn+NzUTnZKZrssEDyXrAzPX+euF9no/ja4Rw8DmAriCjP5Ob7GDZtPVK09ytKBnvliufYhoALKQomiMiuJ4otSTWlerSa/dqjAv34wkw3HyWI3Xg57ejm7w4vhfhylRC/aeerfejnRp0VstgIAm7npBH0UkZM6AtXkOiJF1qBBPANiKvkM/2opbHbh+S5lf/XqC7VY80CwqPnoMSsxh43CDnCY4U4sINKkBfnaZhJAtlAxigGCFxjj81dLIeEyNGBTtyoMSc5EHYxmtmMdsbwfD4zQUM6CHTmUMENHgO5qb3HlGr0x+gocHSZ4EPlkw17GIDGPAmCHhu7zFKb07mHXL9gjUjwwZ2xSfWEaCEV2rJh8d/usyO9qIz0uzG77mooP+z9K5mrT3ibrQMsNSFDya82R/6Okx3Yoa3V0aRxoF8s=
